use std::task::{Context, Poll};
use axum::extract::Request;
use axum::response::Response;
use futures_util::future::BoxFuture;
use tower_layer::Layer;
use tower_service::Service;
use crate::logger::{EventLogger, LoggerHandle};

/// Tower layer for evlog Axum integration.
///
/// Attaches a `LoggerHandle` to every request and emits a wide event upon completion.
#[derive(Clone)]
pub struct EvlogLayer;

impl<S> Layer<S> for EvlogLayer {
    type Service = EvlogService<S>;

    fn layer(&self, inner: S) -> Self::Service {
        EvlogService { inner }
    }
}

#[derive(Clone)]
pub struct EvlogService<S> {
    inner: S,
}

impl<S> Service<Request> for EvlogService<S>
where
    S: Service<Request, Response = Response> + Send + Clone + 'static,
    S::Future: Send + 'static,
{
    type Response = S::Response;
    type Error = S::Error;
    type Future = BoxFuture<'static, Result<Self::Response, Self::Error>>;

    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        self.inner.poll_ready(cx)
    }

    fn call(&mut self, mut req: Request) -> Self::Future {
        let method = req.method().to_string();
        let path = req.uri().path().to_string();

        let mut logger = EventLogger::with_request(method, &path);
        
        if !crate::config::global_config().middleware.should_log(&path) {
            logger.skip_emit = true;
        }

        let handle = LoggerHandle::new(logger);

        // Inject the handle into the request extensions.
        // This allows user-defined route handlers to extract the `LoggerHandle`
        // and enrich the event (e.g. adding a "user_id" field) during the request.
        req.extensions_mut().insert(handle.clone());

        let mut inner = self.inner.clone();

        // Tower middlewares must return a `Future` yielding a Response. 
        // We box it to hide the complex state machine types generated by `async move`.
        Box::pin(async move {
            // 1. Process the inner request (route handlers, other middlewares)
            let res = inner.call(req).await;
            
            // 2. We regain control. Lock the logger to append the response status.
            let mut log = handle.lock();
            match &res {
                Ok(response) => {
                    log.set_status(response.status().as_u16());
                }
                Err(_) => {
                    log.set_status(500);
                }
            }
            log.emit();
            res
        })
    }
}

impl axum::response::IntoResponse for crate::error::EvlogError {
    fn into_response(self) -> Response {
        let status = axum::http::StatusCode::from_u16(self.status)
            .unwrap_or(axum::http::StatusCode::INTERNAL_SERVER_ERROR);
        let body = self.to_response_body();
        (
            status,
            [(axum::http::header::CONTENT_TYPE, "application/json")],
            body,
        ).into_response()
    }
}
